language: julia
os:               # Travis CI has support for Linux and macOS
  - linux
  - osx
julia:            # Julia versions to run tests on
  - 1.0
  - 1.1
  - nightly
  
script: julia --project -e
	'using Pkg; Pkg.build(); Pkg.test(; coverage=true)'
